### ISSUE TITLE
choose locations window not fitting in display

### ISSUE THREAD

**Issue by petertrichy** [PySimpleGUI/PySimpleGUI-COVID19#3]
"Choose locations" window is not fitting within the display screen of my laptop.
My laptop is HP having Intel Core i3 processor with 4 GB RAM. Windows 64 is my os.

**Comment by MikeTheWatchGuy** [comment]
Can you post a screenshot? What is your screen resolution?

**Comment by PySimpleGUI** [comment]
It measure 940 x 484 on my system:
![image](https://user-images.githubusercontent.com/46163555/77580828-088ed080-6eb3-11ea-8e68-32ede2b86803.png)

Which dimension isn't fitting?

**Comment by petertrichy** [comment]
My screen size-15.6, resolution-1366x768
![Untitled](https://user-images.githubusercontent.com/4464626/77615843-50b2ff00-6f56-11ea-8d2b-df80d8edeb54.png)

**Comment by PySimpleGUI** [comment]
OK, it looks like you can handle another column, so I bumped it up.  Please try this version and lemme know how it does.
[COVID19_Confirmed_Cases_Graphs.py.txt](https://github.com/PySimpleGUI/PySimpleGUI-COVID19/files/4386755/COVID19_Confirmed_Cases_Graphs.py.txt)

**Comment by PySimpleGUI** [comment]
925x640...

![image](https://user-images.githubusercontent.com/46163555/77640535-ef2c6980-6f30-11ea-98c7-a9a2797ff7fe.png)

This compresses the window by removing whitespace.  Also dropped the font down to size of 9.  Let me know how it looks and I'll get it checked in.

[COVID19_Confirmed_Cases_Graphs.py.txt](https://github.com/PySimpleGUI/PySimpleGUI-COVID19/files/4386768/COVID19_Confirmed_Cases_Graphs.py.txt)

**Comment by petertrichy** [comment]
OK! It's good and resolved the issue for me. Thanks for responding.
![Uploading COVID19_ChooseLocations.png…]()
